# preload = ~/Pictures/wallpapers/Fuji-Dark.png
wallpaper {
  monitor = DP-1
  # path = ~/Pictures/wallpapers/Fuji-Dark.png
  # path = ~/Pictures/wallpapers/Frieren-Light.jpg
  # path = ~/Pictures/wallpapers/Cat-Pond-Dark.jpg
  path = ~/Pictures/wallpapers/Koi.png
}

splash = false
